package cp.utils.enums;

public enum TransactionType {
	INTERN_SAME_CURRENCY,
	INTERN_DIFF_CURRENCY,
	CURR_SAVINGS_SAME_CURRENCY,
	CURR_SAVINGS_DIFF_CURRENCY,
	SAVINGS_CURR_SAME_CURRENCY,
	SAVINGS_CURR_DIFF_CURRENCY,
	CURR_CREDIT_SAME_CURRENCY,
	CURR_CREDIT_DIFF_CURRENCY,
}
