DROP TABLE IF EXISTS TOKEN_ASIGNEMENTS;
DROP TABLE IF EXISTS CARD_ASIGNEMENTS;
DROP TABLE IF EXISTS ACC_ASIGNEMENTS;
DROP TABLE IF EXISTS CARDS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS COMMISIONS;
DROP TABLE IF EXISTS RATES;
DROP TABLE IF EXISTS USERS_IB;
DROP TABLE IF EXISTS TOKENS;
DROP TABLE IF EXISTS USERS_CCP;
DROP TABLE IF EXISTS EXCHANGE_RATES;

CREATE TABLE COMMISIONS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    comm_type VARCHAR(30) NOT NULL,
    amount DOUBLE(16,4) NOT NULL,
    comm_details VARCHAR(100),
    creation_date TIMESTAMP
);

CREATE TABLE RATES (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rate_type VARCHAR(30) NOT NULL,
    year_percentage DOUBLE(16,4) NOT NULL,
    rate_details VARCHAR(100),
    creation_date TIMESTAMP
);

CREATE TABLE USERS_IB (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    CNP VARCHAR(13) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(100),
    telephone VARCHAR(15),
    auth_type VARCHAR(30),
    creation_date TIMESTAMP
);

CREATE TABLE ACCOUNTS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IBAN VARCHAR(34) NOT NULL,
    acc_type VARCHAR(30) NOT NULL,
    id_comm_admin INT(6) UNSIGNED NOT NULL,
    currency VARCHAR(5) NOT NULL,
    id_rate INT(6) UNSIGNED NOT NULL,
    creation_date TIMESTAMP,
    FOREIGN KEY (id_comm_admin) REFERENCES COMMISIONS(id),
    FOREIGN KEY (id_rate) REFERENCES RATES(id)
);

CREATE TABLE CARDS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    card_no VARCHAR(16) NOT NULL,
    card_type VARCHAR(30) NOT NULL,
    valid_to DATE NOT NULL,
    id_rate INT(6) UNSIGNED NOT NULL, 
    creation_date TIMESTAMP,
    FOREIGN KEY (id_rate) REFERENCES RATES(id)
);

CREATE TABLE TRANSACTIONS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payer_IBAN VARCHAR(34) NOT NULL,
    beneficiary_IBAN VARCHAR(34) NOT NULL,
    trans_type VARCHAR(30) NOT NULL,
    amount DOUBLE(16,4) NOT NULL,
    id_trans_comm INT(6) UNSIGNED NOT NULL,
    payments_details VARCHAR(100),
    creation_date TIMESTAMP,
    FOREIGN KEY (id_trans_comm) REFERENCES COMMISIONS(id)
);

CREATE TABLE TOKENS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    serial VARCHAR(10) NOT NULL,
    token_type VARCHAR(30) NOT NULL,
    creation_date TIMESTAMP
);

CREATE TABLE ACC_ASIGNEMENTS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_user INT(6) UNSIGNED NOT NULL,
    id_acc INT(6) UNSIGNED NOT NULL,
    creation_date TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES USERS_IB(id),
    FOREIGN KEY (id_acc) REFERENCES ACCOUNTS(id)
);

CREATE TABLE CARD_ASIGNEMENTS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_user INT(6) UNSIGNED NOT NULL,
    id_card INT(6) UNSIGNED NOT NULL,
    id_acc INT(6) UNSIGNED NOT NULL,
    creation_date TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES USERS_IB(id),
    FOREIGN KEY (id_card) REFERENCES CARDS(id),
    FOREIGN KEY (id_acc) REFERENCES ACCOUNTS(id)
);

CREATE TABLE TOKEN_ASIGNEMENTS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_token INT(6) UNSIGNED NOT NULL,
    id_user INT(6) UNSIGNED NOT NULL,
    creation_date TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES USERS_IB(id),
    FOREIGN KEY (id_token) REFERENCES TOKENS(id)
);

CREATE TABLE USERS_CCP (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    CNP VARCHAR(13) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(100),
    telephone VARCHAR(15),
    creation_date TIMESTAMP
);

CREATE TABLE EXCHANGE_RATES (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    currency VARCHAR(5) NOT NULL,
    sell DOUBLE(16,4) NOT NULL,
    buy DOUBLE(16,4) NOT NULL,
    creation_date TIMESTAMP
);

INSERT INTO USERS_CCP values (NULL, 'admin', 'admin', 'N/A', 'N/A', 'N/A', 'admin@ebank.com', 'N/A', 'N/A', NULL);

INSERT INTO RATES values (NULL, 'N/A', 0, 'False rate (no rate for debit card and false account)', NULL);

INSERT INTO COMMISIONS values (NULL, 'N/A', 0, 'False commision (nocommision for false account)', NULL);

INSERT INTO ACCOUNTS values (NULL, 'N/A', 'N/A', 1, 'N/A', 1, NULL);
